#!/usr/bin/python
# -*- coding: utf-8 -*-
# Author: Jeremy Parks
# Note: Requires Python 3.7.x or newer
bases = {
	"Crude Bow": "Bow",
	"Short Bow": "Bow",
	"Long Bow": "Bow",
	"Composite Bow": "Bow",
	"Recurve Bow": "Bow",
	"Bone Bow": "Bow",
	"Royal Bow": "Bow",
	"Death Bow": "Bow",
	"Grove Bow": "Bow",
	"Reflex Bow": "Bow",
	"Decurve Bow": "Bow",
	"Compound Bow": "Bow",
	"Sniper Bow": "Bow",
	"Ivory Bow": "Bow",
	"Highborn Bow": "Bow",
	"Decimation Bow": "Bow",
	"Thicket Bow": "Bow",
	"Steelwood Bow": "Bow",
	"Citadel Bow": "Bow",
	"Ranger Bow": "Bow",
	"Assassin Bow": "Bow",
	"Spine Bow": "Bow",
	"Imperial Bow": "Bow",
	"Harbinger Bow": "Bow",
	"Maraketh Bow": "Bow",
	"Nailed Fist": "Claw",
	"Sharktooth Claw": "Claw",
	"Awl": "Claw",
	"Cat's Paw": "Claw",
	"Blinder": "Claw",
	"Timeworn Claw": "Claw",
	"Sparkling Claw": "Claw",
	"Fright Claw": "Claw",
	"Double Claw": "Claw",
	"Thresher Claw": "Claw",
	"Gouger": "Claw",
	"Tiger's Paw": "Claw",
	"Gut Ripper": "Claw",
	"Prehistoric Claw": "Claw",
	"Noble Claw": "Claw",
	"Eagle Claw": "Claw",
	"Twin Claw": "Claw",
	"Great White Claw": "Claw",
	"Throat Stabber": "Claw",
	"Hellion's Paw": "Claw",
	"Eye Gouger": "Claw",
	"Vaal Claw": "Claw",
	"Imperial Claw": "Claw",
	"Terror Claw": "Claw",
	"Gemini Claw": "Claw",
	"Glass Shank": "Dagger",
	"Skinning Knife": "Dagger",
	"Carving Knife": "Dagger",
	"Stiletto": "Dagger",
	"Boot Knife": "Dagger",
	"Copper Kris": "Dagger",
	"Skean": "Dagger",
	"Imp Dagger": "Dagger",
	"Flaying Knife": "Dagger",
	"Prong Dagger": "Dagger",
	"Butcher Knife": "Dagger",
	"Poignard": "Dagger",
	"Boot Blade": "Dagger",
	"Golden Kris": "Dagger",
	"Royal Skean": "Dagger",
	"Fiend Dagger": "Dagger",
	"Trisula": "Dagger",
	"Gutting Knife": "Dagger",
	"Slaughter Knife": "Dagger",
	"Ambusher": "Dagger",
	"Ezomyte Dagger": "Dagger",
	"Platinum Kris": "Dagger",
	"Imperial Skean": "Dagger",
	"Demon Dagger": "Dagger",
	"Sai": "Dagger",
	"Rusted Hatchet": "One Hand Axe",
	"Jade Hatchet": "One Hand Axe",
	"Boarding Axe": "One Hand Axe",
	"Cleaver": "One Hand Axe",
	"Broad Axe": "One Hand Axe",
	"Arming Axe": "One Hand Axe",
	"Decorative Axe": "One Hand Axe",
	"Spectral Axe": "One Hand Axe",
	"Etched Hatchet": "One Hand Axe",
	"Jasper Axe": "One Hand Axe",
	"Tomahawk": "One Hand Axe",
	"Wrist Chopper": "One Hand Axe",
	"War Axe": "One Hand Axe",
	"Chest Splitter": "One Hand Axe",
	"Ceremonial Axe": "One Hand Axe",
	"Wraith Axe": "One Hand Axe",
	"Engraved Hatchet": "One Hand Axe",
	"Karui Axe": "One Hand Axe",
	"Siege Axe": "One Hand Axe",
	"Reaver Axe": "One Hand Axe",
	"Butcher Axe": "One Hand Axe",
	"Vaal Hatchet": "One Hand Axe",
	"Royal Axe": "One Hand Axe",
	"Infernal Axe": "One Hand Axe",
	"Runic Hatchet": "One Hand Axe",
	"Driftwood Club": "One Hand Mace",
	"Tribal Club": "One Hand Mace",
	"Spiked Club": "One Hand Mace",
	"Stone Hammer": "One Hand Mace",
	"War Hammer": "One Hand Mace",
	"Bladed Mace": "One Hand Mace",
	"Ceremonial Mace": "One Hand Mace",
	"Dream Mace": "One Hand Mace",
	"Wyrm Mace": "One Hand Mace",
	"Petrified Club": "One Hand Mace",
	"Barbed Club": "One Hand Mace",
	"Rock Breaker": "One Hand Mace",
	"Battle Hammer": "One Hand Mace",
	"Flanged Mace": "One Hand Mace",
	"Ornate Mace": "One Hand Mace",
	"Phantom Mace": "One Hand Mace",
	"Dragon Mace": "One Hand Mace",
	"Ancestral Club": "One Hand Mace",
	"Tenderizer": "One Hand Mace",
	"Gavel": "One Hand Mace",
	"Legion Hammer": "One Hand Mace",
	"Pernarch": "One Hand Mace",
	"Auric Mace": "One Hand Mace",
	"Nightmare Mace": "One Hand Mace",
	"Behemoth Mace": "One Hand Mace",
	"Rusted Sword": "One Hand Sword",
	"Copper Sword": "One Hand Sword",
	"Sabre": "One Hand Sword",
	"Broad Sword": "One Hand Sword",
	"War Sword": "One Hand Sword",
	"Ancient Sword": "One Hand Sword",
	"Elegant Sword": "One Hand Sword",
	"Dusk Blade": "One Hand Sword",
	"Hook Sword": "One Hand Sword",
	"Variscite Blade": "One Hand Sword",
	"Cutlass": "One Hand Sword",
	"Baselard": "One Hand Sword",
	"Battle Sword": "One Hand Sword",
	"Elder Sword": "One Hand Sword",
	"Graceful Sword": "One Hand Sword",
	"Twilight Blade": "One Hand Sword",
	"Grappler": "One Hand Sword",
	"Gemstone Sword": "One Hand Sword",
	"Corsair Sword": "One Hand Sword",
	"Gladius": "One Hand Sword",
	"Legion Sword": "One Hand Sword",
	"Vaal Blade": "One Hand Sword",
	"Eternal Sword": "One Hand Sword",
	"Midnight Blade": "One Hand Sword",
	"Tiger Hook": "One Hand Sword",
	"Driftwood Sceptre": "Sceptre",
	"Darkwood Sceptre": "Sceptre",
	"Bronze Sceptre": "Sceptre",
	"Quartz Sceptre": "Sceptre",
	"Iron Sceptre": "Sceptre",
	"Ochre Sceptre": "Sceptre",
	"Ritual Sceptre": "Sceptre",
	"Shadow Sceptre": "Sceptre",
	"Grinning Fetish": "Sceptre",
	"Horned Sceptre": "Sceptre",
	"Sekhem": "Sceptre",
	"Crystal Sceptre": "Sceptre",
	"Lead Sceptre": "Sceptre",
	"Blood Sceptre": "Sceptre",
	"Royal Sceptre": "Sceptre",
	"Abyssal Sceptre": "Sceptre",
	"Stag Sceptre": "Sceptre",
	"Karui Sceptre": "Sceptre",
	"Tyrant's Sekhem": "Sceptre",
	"Opal Sceptre": "Sceptre",
	"Platinum Sceptre": "Sceptre",
	"Vaal Sceptre": "Sceptre",
	"Carnal Sceptre": "Sceptre",
	"Void Sceptre": "Sceptre",
	"Sambar Sceptre": "Sceptre",
	"Gnarled Branch": "Staff",
	"Primitive Staff": "Staff",
	"Long Staff": "Staff",
	"Iron Staff": "Staff",
	"Coiled Staff": "Staff",
	"Royal Staff": "Staff",
	"Vile Staff": "Staff",
	"Crescent Staff": "Staff",
	"Woodful Staff": "Staff",
	"Quarterstaff": "Staff",
	"Military Staff": "Staff",
	"Serpentine Staff": "Staff",
	"Highborn Staff": "Staff",
	"Foul Staff": "Staff",
	"Moon Staff": "Staff",
	"Primordial Staff": "Staff",
	"Lathi": "Staff",
	"Ezomyte Staff": "Staff",
	"Maelström Staff": "Staff",
	"Imperial Staff": "Staff",
	"Judgement Staff": "Staff",
	"Eclipse Staff": "Staff",
	"Rusted Spike": "Thrusting One Hand Sword",
	"Whalebone Rapier": "Thrusting One Hand Sword",
	"Battered Foil": "Thrusting One Hand Sword",
	"Basket Rapier": "Thrusting One Hand Sword",
	"Jagged Foil": "Thrusting One Hand Sword",
	"Antique Rapier": "Thrusting One Hand Sword",
	"Elegant Foil": "Thrusting One Hand Sword",
	"Thorn Rapier": "Thrusting One Hand Sword",
	"Smallsword": "Thrusting One Hand Sword",
	"Wyrmbone Rapier": "Thrusting One Hand Sword",
	"Burnished Foil": "Thrusting One Hand Sword",
	"Estoc": "Thrusting One Hand Sword",
	"Serrated Foil": "Thrusting One Hand Sword",
	"Primeval Rapier": "Thrusting One Hand Sword",
	"Fancy Foil": "Thrusting One Hand Sword",
	"Apex Rapier": "Thrusting One Hand Sword",
	"Courtesan Sword": "Thrusting One Hand Sword",
	"Dragonbone Rapier": "Thrusting One Hand Sword",
	"Tempered Foil": "Thrusting One Hand Sword",
	"Pecoraro": "Thrusting One Hand Sword",
	"Spiraled Foil": "Thrusting One Hand Sword",
	"Vaal Rapier": "Thrusting One Hand Sword",
	"Jewelled Foil": "Thrusting One Hand Sword",
	"Harpy Rapier": "Thrusting One Hand Sword",
	"Dragoon Sword": "Thrusting One Hand Sword",
	"Stone Axe": "Two Hand Axe",
	"Jade Chopper": "Two Hand Axe",
	"Woodsplitter": "Two Hand Axe",
	"Poleaxe": "Two Hand Axe",
	"Double Axe": "Two Hand Axe",
	"Gilded Axe": "Two Hand Axe",
	"Shadow Axe": "Two Hand Axe",
	"Dagger Axe": "Two Hand Axe",
	"Jasper Chopper": "Two Hand Axe",
	"Timber Axe": "Two Hand Axe",
	"Headsman Axe": "Two Hand Axe",
	"Labrys": "Two Hand Axe",
	"Noble Axe": "Two Hand Axe",
	"Abyssal Axe": "Two Hand Axe",
	"Karui Chopper": "Two Hand Axe",
	"Talon Axe": "Two Hand Axe",
	"Sundering Axe": "Two Hand Axe",
	"Ezomyte Axe": "Two Hand Axe",
	"Vaal Axe": "Two Hand Axe",
	"Despot Axe": "Two Hand Axe",
	"Void Axe": "Two Hand Axe",
	"Fleshripper": "Two Hand Axe",
	"Driftwood Maul": "Two Hand Mace",
	"Tribal Maul": "Two Hand Mace",
	"Mallet": "Two Hand Mace",
	"Sledgehammer": "Two Hand Mace",
	"Jagged Maul": "Two Hand Mace",
	"Brass Maul": "Two Hand Mace",
	"Fright Maul": "Two Hand Mace",
	"Morning Star": "Two Hand Mace",
	"Totemic Maul": "Two Hand Mace",
	"Great Mallet": "Two Hand Mace",
	"Steelhead": "Two Hand Mace",
	"Spiny Maul": "Two Hand Mace",
	"Plated Maul": "Two Hand Mace",
	"Dread Maul": "Two Hand Mace",
	"Solar Maul": "Two Hand Mace",
	"Karui Maul": "Two Hand Mace",
	"Colossus Mallet": "Two Hand Mace",
	"Piledriver": "Two Hand Mace",
	"Meatgrinder": "Two Hand Mace",
	"Imperial Maul": "Two Hand Mace",
	"Terror Maul": "Two Hand Mace",
	"Coronal Maul": "Two Hand Mace",
	"Corroded Blade": "Two Hand Sword",
	"Longsword": "Two Hand Sword",
	"Bastard Sword": "Two Hand Sword",
	"Two-Handed Sword": "Two Hand Sword",
	"Etched Greatsword": "Two Hand Sword",
	"Ornate Sword": "Two Hand Sword",
	"Spectral Sword": "Two Hand Sword",
	"Curved Blade": "Two Hand Sword",
	"Butcher Sword": "Two Hand Sword",
	"Footman Sword": "Two Hand Sword",
	"Highland Blade": "Two Hand Sword",
	"Engraved Greatsword": "Two Hand Sword",
	"Tiger Sword": "Two Hand Sword",
	"Wraith Sword": "Two Hand Sword",
	"Lithe Blade": "Two Hand Sword",
	"Headman's Sword": "Two Hand Sword",
	"Reaver Sword": "Two Hand Sword",
	"Ezomyte Blade": "Two Hand Sword",
	"Vaal Greatsword": "Two Hand Sword",
	"Lion Sword": "Two Hand Sword",
	"Infernal Sword": "Two Hand Sword",
	"Exquisite Blade": "Two Hand Sword",
	"Driftwood Wand": "Wand",
	"Goat's Horn": "Wand",
	"Carved Wand": "Wand",
	"Quartz Wand": "Wand",
	"Spiraled Wand": "Wand",
	"Sage Wand": "Wand",
	"Pagan Wand": "Wand",
	"Faun's Horn": "Wand",
	"Engraved Wand": "Wand",
	"Crystal Wand": "Wand",
	"Serpent Wand": "Wand",
	"Omen Wand": "Wand",
	"Heathen Wand": "Wand",
	"Demon's Horn": "Wand",
	"Imbued Wand": "Wand",
	"Opal Wand": "Wand",
	"Tornado Wand": "Wand",
	"Prophecy Wand": "Wand",
	"Profane Wand": "Wand",
	"Plate Vest": "Body Armour",
	"Chestplate": "Body Armour",
	"Copper Plate": "Body Armour",
	"War Plate": "Body Armour",
	"Full Plate": "Body Armour",
	"Arena Plate": "Body Armour",
	"Lordly Plate": "Body Armour",
	"Bronze Plate": "Body Armour",
	"Battle Plate": "Body Armour",
	"Sun Plate": "Body Armour",
	"Colosseum Plate": "Body Armour",
	"Majestic Plate": "Body Armour",
	"Golden Plate": "Body Armour",
	"Crusader Plate": "Body Armour",
	"Astral Plate": "Body Armour",
	"Gladiator Plate": "Body Armour",
	"Glorious Plate": "Body Armour",
	"Shabby Jerkin": "Body Armour",
	"Strapped Leather": "Body Armour",
	"Buckskin Tunic": "Body Armour",
	"Wild Leather": "Body Armour",
	"Full Leather": "Body Armour",
	"Sun Leather": "Body Armour",
	"Thief's Garb": "Body Armour",
	"Eelskin Tunic": "Body Armour",
	"Frontier Leather": "Body Armour",
	"Glorious Leather": "Body Armour",
	"Coronal Leather": "Body Armour",
	"Cutthroat's Garb": "Body Armour",
	"Sharkskin Tunic": "Body Armour",
	"Destiny Leather": "Body Armour",
	"Exquisite Leather": "Body Armour",
	"Zodiac Leather": "Body Armour",
	"Assassin's Garb": "Body Armour",
	"Simple Robe": "Body Armour",
	"Silken Vest": "Body Armour",
	"Scholar's Robe": "Body Armour",
	"Silken Garb": "Body Armour",
	"Mage's Vestment": "Body Armour",
	"Silk Robe": "Body Armour",
	"Cabalist Regalia": "Body Armour",
	"Sage's Robe": "Body Armour",
	"Silken Wrap": "Body Armour",
	"Conjurer's Vestment": "Body Armour",
	"Spidersilk Robe": "Body Armour",
	"Destroyer Regalia": "Body Armour",
	"Savant's Robe": "Body Armour",
	"Necromancer Silks": "Body Armour",
	"Occultist's Vestment": "Body Armour",
	"Widowsilk Robe": "Body Armour",
	"Vaal Regalia": "Body Armour",
	"Padded Vest": "Body Armour",
	"Oiled Vest": "Body Armour",
	"Padded Jacket": "Body Armour",
	"Oiled Coat": "Body Armour",
	"Scarlet Raiment": "Body Armour",
	"Waxed Garb": "Body Armour",
	"Bone Armour": "Body Armour",
	"Quilted Jacket": "Body Armour",
	"Sleek Coat": "Body Armour",
	"Crimson Raiment": "Body Armour",
	"Lacquered Garb": "Body Armour",
	"Crypt Armour": "Body Armour",
	"Sentinel Jacket": "Body Armour",
	"Varnished Coat": "Body Armour",
	"Blood Raiment": "Body Armour",
	"Sadist Garb": "Body Armour",
	"Carnal Armour": "Body Armour",
	"Chainmail Vest": "Body Armour",
	"Chainmail Tunic": "Body Armour",
	"Ringmail Coat": "Body Armour",
	"Chainmail Doublet": "Body Armour",
	"Full Ringmail": "Body Armour",
	"Full Chainmail": "Body Armour",
	"Holy Chainmail": "Body Armour",
	"Latticed Ringmail": "Body Armour",
	"Crusader Chainmail": "Body Armour",
	"Ornate Ringmail": "Body Armour",
	"Chain Hauberk": "Body Armour",
	"Devout Chainmail": "Body Armour",
	"Loricated Ringmail": "Body Armour",
	"Conquest Chainmail": "Body Armour",
	"Elegant Ringmail": "Body Armour",
	"Saint's Hauberk": "Body Armour",
	"Saintly Chainmail": "Body Armour",
	"Scale Vest": "Body Armour",
	"Light Brigandine": "Body Armour",
	"Scale Doublet": "Body Armour",
	"Infantry Brigandine": "Body Armour",
	"Full Scale Armour": "Body Armour",
	"Soldier's Brigandine": "Body Armour",
	"Field Lamellar": "Body Armour",
	"Wyrmscale Doublet": "Body Armour",
	"Hussar Brigandine": "Body Armour",
	"Full Wyrmscale": "Body Armour",
	"Commander's Brigandine": "Body Armour",
	"Battle Lamellar": "Body Armour",
	"Dragonscale Doublet": "Body Armour",
	"Desert Brigandine": "Body Armour",
	"Full Dragonscale": "Body Armour",
	"General's Brigandine": "Body Armour",
	"Triumphant Lamellar": "Body Armour",
	"Sacrificial Garb": "Body Armour",
	"Iron Greaves": "Boots",
	"Steel Greaves": "Boots",
	"Plated Greaves": "Boots",
	"Reinforced Greaves": "Boots",
	"Antique Greaves": "Boots",
	"Ancient Greaves": "Boots",
	"Goliath Greaves": "Boots",
	"Vaal Greaves": "Boots",
	"Titan Greaves": "Boots",
	"Wool Shoes": "Boots",
	"Velvet Slippers": "Boots",
	"Silk Slippers": "Boots",
	"Scholar Boots": "Boots",
	"Satin Slippers": "Boots",
	"Samite Slippers": "Boots",
	"Conjurer Boots": "Boots",
	"Arcanist Slippers": "Boots",
	"Sorcerer Boots": "Boots",
	"Rawhide Boots": "Boots",
	"Goathide Boots": "Boots",
	"Deerskin Boots": "Boots",
	"Nubuck Boots": "Boots",
	"Eelskin Boots": "Boots",
	"Sharkskin Boots": "Boots",
	"Shagreen Boots": "Boots",
	"Stealth Boots": "Boots",
	"Slink Boots": "Boots",
	"Chain Boots": "Boots",
	"Ringmail Boots": "Boots",
	"Mesh Boots": "Boots",
	"Riveted Boots": "Boots",
	"Zealot Boots": "Boots",
	"Soldier Boots": "Boots",
	"Legion Boots": "Boots",
	"Crusader Boots": "Boots",
	"Wrapped Boots": "Boots",
	"Strapped Boots": "Boots",
	"Clasped Boots": "Boots",
	"Shackled Boots": "Boots",
	"Trapper Boots": "Boots",
	"Ambush Boots": "Boots",
	"Carnal Boots": "Boots",
	"Assassin's Boots": "Boots",
	"Murder Boots": "Boots",
	"Leatherscale Boots": "Boots",
	"Ironscale Boots": "Boots",
	"Bronzescale Boots": "Boots",
	"Steelscale Boots": "Boots",
	"Serpentscale Boots": "Boots",
	"Wyrmscale Boots": "Boots",
	"Hydrascale Boots": "Boots",
	"Dragonscale Boots": "Boots",
	"Two-Toned Boots": "Boots",
	"Iron Gauntlets": "Gloves",
	"Plated Gauntlets": "Gloves",
	"Bronze Gauntlets": "Gloves",
	"Steel Gauntlets": "Gloves",
	"Antique Gauntlets": "Gloves",
	"Ancient Gauntlets": "Gloves",
	"Goliath Gauntlets": "Gloves",
	"Vaal Gauntlets": "Gloves",
	"Titan Gauntlets": "Gloves",
	"Spiked Gloves": "Gloves",
	"Rawhide Gloves": "Gloves",
	"Goathide Gloves": "Gloves",
	"Deerskin Gloves": "Gloves",
	"Nubuck Gloves": "Gloves",
	"Eelskin Gloves": "Gloves",
	"Sharkskin Gloves": "Gloves",
	"Shagreen Gloves": "Gloves",
	"Stealth Gloves": "Gloves",
	"Slink Gloves": "Gloves",
	"Gripped Gloves": "Gloves",
	"Wool Gloves": "Gloves",
	"Velvet Gloves": "Gloves",
	"Silk Gloves": "Gloves",
	"Embroidered Gloves": "Gloves",
	"Satin Gloves": "Gloves",
	"Samite Gloves": "Gloves",
	"Conjurer Gloves": "Gloves",
	"Arcanist Gloves": "Gloves",
	"Sorcerer Gloves": "Gloves",
	"Fingerless Silk Gloves": "Gloves",
	"Fishscale Gauntlets": "Gloves",
	"Ironscale Gauntlets": "Gloves",
	"Bronzescale Gauntlets": "Gloves",
	"Steelscale Gauntlets": "Gloves",
	"Serpentscale Gauntlets": "Gloves",
	"Wyrmscale Gauntlets": "Gloves",
	"Hydrascale Gauntlets": "Gloves",
	"Dragonscale Gauntlets": "Gloves",
	"Wrapped Mitts": "Gloves",
	"Strapped Mitts": "Gloves",
	"Clasped Mitts": "Gloves",
	"Trapper Mitts": "Gloves",
	"Ambush Mitts": "Gloves",
	"Carnal Mitts": "Gloves",
	"Assassin's Mitts": "Gloves",
	"Murder Mitts": "Gloves",
	"Chain Gloves": "Gloves",
	"Ringmail Gloves": "Gloves",
	"Mesh Gloves": "Gloves",
	"Riveted Gloves": "Gloves",
	"Zealot Gloves": "Gloves",
	"Soldier Gloves": "Gloves",
	"Legion Gloves": "Gloves",
	"Crusader Gloves": "Gloves",
	"Iron Hat": "Helmet",
	"Cone Helmet": "Helmet",
	"Barbute Helmet": "Helmet",
	"Close Helmet": "Helmet",
	"Gladiator Helmet": "Helmet",
	"Reaver Helmet": "Helmet",
	"Siege Helmet": "Helmet",
	"Samite Helmet": "Helmet",
	"Ezomyte Burgonet": "Helmet",
	"Royal Burgonet": "Helmet",
	"Eternal Burgonet": "Helmet",
	"Leather Cap": "Helmet",
	"Tricorne": "Helmet",
	"Leather Hood": "Helmet",
	"Wolf Pelt": "Helmet",
	"Hunter Hood": "Helmet",
	"Noble Tricorne": "Helmet",
	"Ursine Pelt": "Helmet",
	"Silken Hood": "Helmet",
	"Sinner Tricorne": "Helmet",
	"Lion Pelt": "Helmet",
	"Vine Circlet": "Helmet",
	"Iron Circlet": "Helmet",
	"Torture Cage": "Helmet",
	"Tribal Circlet": "Helmet",
	"Bone Circlet": "Helmet",
	"Lunaris Circlet": "Helmet",
	"Steel Circlet": "Helmet",
	"Necromancer Circlet": "Helmet",
	"Solaris Circlet": "Helmet",
	"Mind Cage": "Helmet",
	"Hubris Circlet": "Helmet",
	"Scare Mask": "Helmet",
	"Plague Mask": "Helmet",
	"Iron Mask": "Helmet",
	"Festival Mask": "Helmet",
	"Golden Mask": "Helmet",
	"Raven Mask": "Helmet",
	"Callous Mask": "Helmet",
	"Regicide Mask": "Helmet",
	"Harlequin Mask": "Helmet",
	"Vaal Mask": "Helmet",
	"Deicide Mask": "Helmet",
	"Battered Helm": "Helmet",
	"Sallet": "Helmet",
	"Visored Sallet": "Helmet",
	"Gilded Sallet": "Helmet",
	"Secutor Helm": "Helmet",
	"Fencer Helm": "Helmet",
	"Lacquered Helmet": "Helmet",
	"Fluted Bascinet": "Helmet",
	"Pig-Faced Bascinet": "Helmet",
	"Nightmare Bascinet": "Helmet",
	"Rusted Coif": "Helmet",
	"Soldier Helmet": "Helmet",
	"Great Helmet": "Helmet",
	"Crusader Helmet": "Helmet",
	"Aventail Helmet": "Helmet",
	"Zealot Helmet": "Helmet",
	"Great Crown": "Helmet",
	"Magistrate Crown": "Helmet",
	"Prophet Crown": "Helmet",
	"Praetor Crown": "Helmet",
	"Bone Helmet": "Helmet",
	"Splintered Tower Shield": "Shield",
	"Corroded Tower Shield": "Shield",
	"Rawhide Tower Shield": "Shield",
	"Cedar Tower Shield": "Shield",
	"Copper Tower Shield": "Shield",
	"Reinforced Tower Shield": "Shield",
	"Painted Tower Shield": "Shield",
	"Buckskin Tower Shield": "Shield",
	"Mahogany Tower Shield": "Shield",
	"Bronze Tower Shield": "Shield",
	"Girded Tower Shield": "Shield",
	"Crested Tower Shield": "Shield",
	"Shagreen Tower Shield": "Shield",
	"Ebony Tower Shield": "Shield",
	"Ezomyte Tower Shield": "Shield",
	"Colossal Tower Shield": "Shield",
	"Pinnacle Tower Shield": "Shield",
	"Goathide Buckler": "Shield",
	"Pine Buckler": "Shield",
	"Painted Buckler": "Shield",
	"Hammered Buckler": "Shield",
	"War Buckler": "Shield",
	"Gilded Buckler": "Shield",
	"Oak Buckler": "Shield",
	"Enameled Buckler": "Shield",
	"Corrugated Buckler": "Shield",
	"Battle Buckler": "Shield",
	"Golden Buckler": "Shield",
	"Ironwood Buckler": "Shield",
	"Lacquered Buckler": "Shield",
	"Vaal Buckler": "Shield",
	"Crusader Buckler": "Shield",
	"Imperial Buckler": "Shield",
	"Twig Spirit Shield": "Shield",
	"Yew Spirit Shield": "Shield",
	"Bone Spirit Shield": "Shield",
	"Tarnished Spirit Shield": "Shield",
	"Jingling Spirit Shield": "Shield",
	"Brass Spirit Shield": "Shield",
	"Walnut Spirit Shield": "Shield",
	"Ivory Spirit Shield": "Shield",
	"Ancient Spirit Shield": "Shield",
	"Chiming Spirit Shield": "Shield",
	"Thorium Spirit Shield": "Shield",
	"Lacewood Spirit Shield": "Shield",
	"Fossilised Spirit Shield": "Shield",
	"Vaal Spirit Shield": "Shield",
	"Harmonic Spirit Shield": "Shield",
	"Titanium Spirit Shield": "Shield",
	"Spiked Bundle": "Shield",
	"Driftwood Spiked Shield": "Shield",
	"Alloyed Spiked Shield": "Shield",
	"Burnished Spiked Shield": "Shield",
	"Ornate Spiked Shield": "Shield",
	"Redwood Spiked Shield": "Shield",
	"Compound Spiked Shield": "Shield",
	"Polished Spiked Shield": "Shield",
	"Sovereign Spiked Shield": "Shield",
	"Alder Spiked Shield": "Shield",
	"Ezomyte Spiked Shield": "Shield",
	"Mirrored Spiked Shield": "Shield",
	"Supreme Spiked Shield": "Shield",
	"Rotted Round Shield": "Shield",
	"Fir Round Shield": "Shield",
	"Studded Round Shield": "Shield",
	"Scarlet Round Shield": "Shield",
	"Splendid Round Shield": "Shield",
	"Maple Round Shield": "Shield",
	"Spiked Round Shield": "Shield",
	"Crimson Round Shield": "Shield",
	"Baroque Round Shield": "Shield",
	"Teak Round Shield": "Shield",
	"Spiny Round Shield": "Shield",
	"Cardinal Round Shield": "Shield",
	"Elegant Round Shield": "Shield",
	"Plank Kite Shield": "Shield",
	"Linden Kite Shield": "Shield",
	"Reinforced Kite Shield": "Shield",
	"Layered Kite Shield": "Shield",
	"Ceremonial Kite Shield": "Shield",
	"Etched Kite Shield": "Shield",
	"Steel Kite Shield": "Shield",
	"Laminated Kite Shield": "Shield",
	"Angelic Kite Shield": "Shield",
	"Branded Kite Shield": "Shield",
	"Champion Kite Shield": "Shield",
	"Mosaic Kite Shield": "Shield",
	"Archon Kite Shield": "Shield",
	"Mandible Talisman": "Amulet",
	"Hexclaw Talisman": "Amulet",
	"Primal Skull Talisman": "Amulet",
	"Wereclaw Talisman": "Amulet",
	"Splitnewt Talisman": "Amulet",
	"Clutching Talisman": "Amulet",
	"Avian Twins Talisman": "Amulet",
	"Fangjaw Talisman": "Amulet",
	"Horned Talisman": "Amulet",
	"Spinefuse Talisman": "Amulet",
	"Three Rat Talisman": "Amulet",
	"Monkey Twins Talisman": "Amulet",
	"Longtooth Talisman": "Amulet",
	"Rotfeather Talisman": "Amulet",
	"Monkey Paw Talisman": "Amulet",
	"Three Hands Talisman": "Amulet",
	"Jet Amulet": "Amulet",
	"Black Maw Talisman": "Amulet",
	"Bonespire Talisman": "Amulet",
	"Ashscale Talisman": "Amulet",
	"Lone Antler Talisman": "Amulet",
	"Deep One Talisman": "Amulet",
	"Breakrib Talisman": "Amulet",
	"Deadhand Talisman": "Amulet",
	"Undying Flesh Talisman": "Amulet",
	"Rot Head Talisman": "Amulet",
	"Paua Amulet": "Amulet",
	"Coral Amulet": "Amulet",
	"Jade Amulet": "Amulet",
	"Amber Amulet": "Amulet",
	"Lapis Amulet": "Amulet",
	"Gold Amulet": "Amulet",
	"Agate Amulet": "Amulet",
	"Turquoise Amulet": "Amulet",
	"Citrine Amulet": "Amulet",
	"Onyx Amulet": "Amulet",
	"Writhing Talisman": "Amulet",
	"Chrysalis Talisman": "Amulet",
	"Ruby Amulet": "Amulet",
	"Marble Amulet": "Amulet",
	"Blue Pearl Amulet": "Amulet",
	"Stygian Vise": "Belt",
	"Rustic Sash": "Belt",
	"Chain Belt": "Belt",
	"Heavy Belt": "Belt",
	"Leather Belt": "Belt",
	"Golden Obi": "Belt",
	"Cloth Belt": "Belt",
	"Studded Belt": "Belt",
	"Vanguard Belt": "Belt",
	"Crystal Belt": "Belt",
	"Breach Ring": "Ring",
	"Iron Ring": "Ring",
	"Coral Ring": "Ring",
	"Paua Ring": "Ring",
	"Sapphire Ring": "Ring",
	"Golden Hoop": "Ring",
	"Topaz Ring": "Ring",
	"Jet Ring": "Ring",
	"Ruby Ring": "Ring",
	"Gold Ring": "Ring",
	"Two-Stone Ring": "Ring",
	"Diamond Ring": "Ring",
	"Moonstone Ring": "Ring",
	"Prismatic Ring": "Ring",
	"Amethyst Ring": "Ring",
	"Unset Ring": "Ring",
	"Opal Ring": "Ring",
	"Steel Ring": "Ring",
	"Cobalt Jewel": "Jewel",
	"Crimson Jewel": "Jewel",
	"Viridian Jewel": "Jewel",
	"Searching Eye Jewel": "Abyss Jewel",
	"Murderous Eye Jewel": "Abyss Jewel",
	"Hypnotic Eye Jewel": "Abyss Jewel",
	"Ghastly Eye Jewel": "Abyss Jewel"
}